### ISSUE TITLE
我的上传 action 代码为...这个可否说的更加详细些?

### ISSUE THREAD

**Issue by wedojava** [yccphp/laravel-5-markdown-editor#1]
你写的这个action方法确实不知道放哪里更好,放控制器中?还是就放在这个editor配置文件里?想快速试试,谢谢指教!

**Comment by endachao** [comment]
目前，上传图片对应的方法，已经移到扩展内部了，我是这样使用的
1. 我有一个公共上传文件的控制器 `backned/uploadFileController`

2.在`config/editor.php` 里面配置 为我的控制器访问地址 

```
    'uploadUrl'=>'backend/upload/img'

```

3.在我的  `backned/uploadFileController` 控制器下的 `img` 代码如下

`头部先引用`

```
use EndaEditor;
```

然后 action如下

```

public function postImg(){
        $data = EndaEditor::uploadImgFile('uploads');
        return json_encode($data);
    }

```

可以看到，我把图片上传移至扩展内部的时候，你已经不用担心如何去写上传图片的代码了，而是考虑把这个请求放在哪的问题了，对于把请求放在哪，这个根据您的需求配置，这个还是挺灵活的

**Comment by endachao** [comment]
目前，上传图片对应的方法，已经移到扩展内部了，我是这样使用的
1. 我有一个公共上传文件的控制器 `backned/uploadFileController`

2.在`config/editor.php` 里面配置 为我的控制器访问地址 

```
    'uploadUrl'=>'backend/upload/img'

```

3.在我的  `backned/uploadFileController` 控制器下的 `img` 代码如下

`头部先引用`

```
use EndaEditor;
```

然后 action如下

```

public function postImg(){
        $data = EndaEditor::uploadImgFile('uploads');
        return json_encode($data);
    }

```

可以看到，我把图片上传移至扩展内部的时候，你已经不用担心如何去写上传图片的代码了，而是考虑把这个请求放在哪的问题了，对于把请求放在哪，这个根据您的需求配置，这个还是挺灵活的

**Comment by endachao** [comment]
其实不用在乎我的action是什么，你只要清楚，下面这句代码会上传图片，并返回数据给编辑器

```

EndaEditor::uploadImgFile('uploads');

```

**Comment by wedojava** [comment]
谢谢解答,我想让客户有上传图片操作时才调用这个方法,我再想想,你的思路我已明白了,谢谢..

**Comment by wenber-yu** [comment]
安装完成后,少了对jquery的引入.按照安装文档安装完成并创建一个editor实例后,报Error: Bootstrap's JavaScript requires jQuery,需要在head.blade.php中引入jquery.js.
