### ISSUE TITLE
fileUpload()方法未定义的错误,解决办法分享

### ISSUE THREAD

**Issue by wedojava** [yccphp/laravel-5-markdown-editor#2]
> 在一个页面多次引入了jq库导致,去掉多引入的jq即可.

![i phpgcm ou7vg81 u5](https://cloud.githubusercontent.com/assets/9837993/7718524/5588e982-fee4-11e4-8ee2-0e9b608a68b7.jpg)

**Comment by endachao** [comment]
感谢分享～
